-- ============================================================
-- Migration 046: story_summaries table
--
-- Stores pre-computed weekly / monthly / yearly narrative summaries
-- so the Explore screen can read rich highlight data at zero AI cost
-- (generated by background jobs, not on-demand per user request).
--
-- weekly  → ≤ 60 words  — derived inline from the generated narrative
-- monthly → ≤ 100 words — synthesised from 4-5 weekly summaries
-- yearly  → ≤ 200 words — synthesised from 12 monthly summaries
-- ============================================================

CREATE TABLE IF NOT EXISTS public.story_summaries (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  period_type  TEXT        NOT NULL CHECK (period_type IN ('weekly', 'monthly', 'yearly')),
  period_start DATE        NOT NULL,   -- Monday for weekly; 1st for monthly; Jan-1 for yearly
  summary      TEXT        NOT NULL,
  top_mood     TEXT,                   -- most common emotion across entries in the period
  top_theme    TEXT,                   -- most common tag across entries in the period
  entry_count  INT         NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT story_summaries_unique UNIQUE (user_id, period_type, period_start)
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS story_summaries_user_period_idx
  ON public.story_summaries (user_id, period_type, period_start DESC);

-- ============================================================
-- Auto-updated_at trigger
-- ============================================================

CREATE TRIGGER story_summaries_updated_at
  BEFORE UPDATE ON public.story_summaries
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ============================================================
-- Row Level Security
-- ============================================================

ALTER TABLE public.story_summaries ENABLE ROW LEVEL SECURITY;

-- Users can only read their own summaries
CREATE POLICY "Users can read own story summaries"
  ON public.story_summaries FOR SELECT
  USING (auth.uid() = user_id);

-- Background service_role jobs write summaries (bypasses RLS)
-- No INSERT/UPDATE policy needed for authenticated users.

-- ============================================================
-- Helper RPC: get_story_summary
-- Returns the most recent summary for a given user + period type.
-- Called by Flutter app — avoids exposing direct table reads.
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_story_summary(
  p_user_id    UUID,
  p_period     TEXT,
  p_year       INT DEFAULT NULL,   -- optional: filter by year
  p_month      INT DEFAULT NULL    -- optional: filter by month (1-12), only for weekly
)
RETURNS TABLE (
  period_start DATE,
  summary      TEXT,
  top_mood     TEXT,
  top_theme    TEXT,
  entry_count  INT,
  updated_at   TIMESTAMPTZ
)
LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
BEGIN
  RETURN QUERY
  SELECT
    ss.period_start,
    ss.summary,
    ss.top_mood,
    ss.top_theme,
    ss.entry_count,
    ss.updated_at
  FROM public.story_summaries ss
  WHERE ss.user_id    = p_user_id
    AND ss.period_type = p_period
    AND (p_year  IS NULL OR EXTRACT(YEAR  FROM ss.period_start) = p_year)
    AND (p_month IS NULL OR EXTRACT(MONTH FROM ss.period_start) = p_month)
  ORDER BY ss.period_start DESC
  LIMIT 1;
END;
$$;

GRANT EXECUTE ON FUNCTION public.get_story_summary TO authenticated;
